IDIR =../include
LDIR =../lib
CC=gcc
CFLAGS=-I$(IDIR)

all:
	$(CC) -pthread -lz -ldl KvsVideoOnlyStreamingSample.c -o main $(CFLAGS) \
	-L$(LDIR) -lcproducer -lkvsCommonCurl -lkvspic -lcurl -lssl -lcrypto

.PHONY: clean

clean:
	rm -f sample