IDIR =../include
LDIR =../lib
CFLAGS=-I$(IDIR) -static
# Please export your Compiler Collection
# CC=xxx-gcc

all:
	$(CC) -pthread -lz -ldl KvsVideoOnlyStreamingSample.c -o main $(CFLAGS) \
	-L$(LDIR) -lcproducer -lkvsCommonCurl -lkvspic -lcurl -lmbedtls -lmbedx509 -lmbedcrypto

.PHONY: clean

clean:
	rm -f main
